### ISSUE TITLE
I got some runtime error, but i'm not sure what's wrong?

### ISSUE THREAD

**Issue by a28218832** [loeweX/Forward-Forward#2]
I followed the description in readme, but under win10. And I got these error. Can someone explain what's happening to me? 

```cmd
seed: 42
device: cuda
input:
  path: datasets
  batch_size: 100
model:
  peer_normalization: 0.03      
  momentum: 0.9
  hidden_dim: 1000
  num_layers: 3
training:
  epochs: 100
  learning_rate: 0.001
  weight_decay: 0.0003
  momentum: 0.9
  downstream_learning_rate: 0.01
  downstream_weight_decay: 0.003
  val_idx: -1
  final_test: false

FF_model(
  (model): ModuleList(
    (0): Linear(in_features=784, out_features=1000, bias=True)
    (1): Linear(in_features=1000, out_features=1000, bias=True)
    (2): Linear(in_features=1000, out_features=1000, bias=True)
  )
  (ff_loss): BCEWithLogitsLoss()
  (linear_classifier): Sequential(
    (0): Linear(in_features=2000, out_features=10, bias=False)
  )
  (classification_loss): CrossEntropyLoss()
) 

Error executing job with overrides: []
Traceback (most recent call last):
  File "C:\my_file\0_research\2023_FF\Forward-Forward\main.py", line 72, in my_main
    model = train(opt, model, optimizer)
  File "C:\my_file\0_research\2023_FF\Forward-Forward\main.py", line 20, in train
    for inputs, labels in train_loader:
  File "C:\Users\User\anaconda3\envs\FF\lib\site-packages\torch\utils\data\dataloader.py", line 530, in __next__
    data = self._next_data()
  File "C:\Users\User\anaconda3\envs\FF\lib\site-packages\torch\utils\data\dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "C:\Users\User\anaconda3\envs\FF\lib\site-packages\torch\utils\data\dataloader.py", line 1250, in _process_data
    data.reraise()
  File "C:\Users\User\anaconda3\envs\FF\lib\site-packages\torch\_utils.py", line 457, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\User\anaconda3\envs\FF\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\User\anaconda3\envs\FF\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\User\anaconda3\envs\FF\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\my_file\0_research\2023_FF\Forward-Forward\src\ff_mnist.py", line 15, in __getitem__
    pos_sample, neg_sample, neutral_sample, class_label = self._generate_sample(
  File "C:\my_file\0_research\2023_FF\Forward-Forward\src\ff_mnist.py", line 58, in _generate_sample
    neg_sample = self._get_neg_sample(sample, class_label)
  File "C:\my_file\0_research\2023_FF\Forward-Forward\src\ff_mnist.py", line 43, in _get_neg_sample
    one_hot_label = torch.nn.functional.one_hot(
RuntimeError: one_hot is only applicable to index tensor.


Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by a28218832** [comment]
Replace line 42, in File "src\ff_mnist.py", in _get_neg_sample
```python=42
        wrong_class_label = np.random.choice(classes)
```
into
```python=42
        wrong_class_label = np.random.choice(classes).astype(np.int64)
```
Because the first attribute of onehot must be LongTensor, which is in int64.
